task:
  matrix:
     - name: linux
       container:
          image: rust:latest
          
     - name: linux(nightly)
       container:
          image: rustlang/rust:nightly
     
     - osx_instance:
          image: mojave-base
       matrix:
          - name: macOS
            install_rust_script: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable && source $HOME/.cargo/env
     
  cargo_cache:
     folder: $CARGO_HOME/registry
  check_script: rustup component add rustfmt && cargo fmt -- --check   
  build_script: cargo build --verbose --all
  test_script: cargo test --verbose --all
  before_cache_script: rm -rf $CARGO_HOME/registry/index
