task:
  matrix:
     - name: linux
       container:
          image: rust:latest
       rustfmt_script: rustup component add rustfmt && cargo fmt -- --check
      
  cargo_cache:
     folder: $CARGO_HOME/registry
  build_script: cargo build --verbose --all
  test_script: cargo test --verbose --all
  before_cache_script: rm -rf $CARGO_HOME/registry/index
