language: rust

rust:
  - stable

os:
  - windows
  - linux
  - osx

branches:
    only:                                                                                             
        - master

install:
  - rustup component add rustfmt

script:
  - cargo fmt -- --check
  - cargo build --verbose --all
  - cargo test --verbose --all
