[package]
name = "sio"
version = "0.1.0"
authors = ["Andreas Auernhammer <aead@mail.de>"]
edition = "2018"

description = "Secure IO"
license = "MIT"

[features]
default = ["ring"]

[dependencies]
ring = { version = "0.14.6", optional = true }
